import dynamic from 'next/dynamic';

// Common exports without dynamic
export { default as BaseComponent } from './BaseComponent';
export { default as Head } from './_base/Head';
export { default as Link } from './_base/Link';
export { default as P } from './_base/Paragraph';
export { default as TextStyle } from './_base/TextStyles';
export { default as Navigation } from './navigation/Navigation';
export { default as Container } from './container/Container';
export { LI, OL, UL } from './_base/Lists';
export {
  H1, H2, H3, H4, H5, H6,
} from './_base/Titles';
export { Grid, Column } from './grid/Grid';

export const Pre = dynamic(() => import('./_base/Pre'));
export const Code = dynamic(() => import('./_base/Code'));
export const Marquee = dynamic(() => import('./_base/Marquee'));
export const SecondaryNavigation = dynamic(() => import('./navigation/SecondaryNavigation'));
export const Alert = dynamic(() => import('./alert/Alert'));
export const Banner = dynamic(() => import('./banner/Banner'));
export const Card = dynamic(() => import('./card/Card'));
export const Dropdown = dynamic(() => import('./dropdown/Dropdown'));
export const Header = dynamic(() => import('./header/Header'));
export const Footer = dynamic(() => import('./footer/Footer'));
export const Blockquote = dynamic(() => import('./_base/Blockquote'));
export const Icon = dynamic(() => import('./_base/Icon'));
export const Badge = dynamic(() => import('./badge/Badge'));
export const Pill = dynamic(() => import('./badge/Pill'));
export const Button = dynamic(() => import('./button/Button'));
export const Image = dynamic(() => import('./image/Image'));
export const Avatars = dynamic(() => import('./avatars/Avatars'));
export const Input = dynamic(() => import('./form/Input'));
export const TextArea = dynamic(() => import('./form/TextArea'));
export const Checkbox = dynamic(() => import('./form/Checkbox'));
export const Select = dynamic(() => import('./form/Select'));
export const Table = dynamic(() => import('./table/Table'));
export const PagedTable = dynamic(() => import('./table/PagedTable'));
export const Section = dynamic(() => import('./section/Section'));
export const TableOfContents = dynamic(() => import('./sidebars/TableOfContents'));
export const Sidebar = dynamic(() => import('./sidebars/Sidebar'));
export const SidebarLink = dynamic(() => import('./sidebars/Sidebar').then((m) => m.SidebarLink));
export const SidebarAccordion = dynamic(() => import('./sidebars/Sidebar').then((m) => m.SidebarAccordion));
export const Tabs = dynamic(() => import('./tabs/Tabs'));
export const Toggle = dynamic(() => import('./form/Toggle'));
export const Tooltip = dynamic(() => import('./tooltip/Tooltip'));
export const Accordion = dynamic(() => import('./accordion/Accordion'));
export const HR = dynamic(() => import('./_base/HR'));
export const Breadcrumb = dynamic(() => import('./breadcrumb/Breadcrumb'));
export const Modal = dynamic(() => import('./modal/Modal'));
export const NavDropdown = dynamic(() => import('./navigation/NavDropdown'));
export const PaginationPrevious = dynamic(() => import('./pagination/PrevNext').then((m) => m.PaginationPrevious));
export const PaginationNext = dynamic(() => import('./pagination/PrevNext').then((m) => m.PaginationNext));
export const FloatLeft = dynamic(() => import('./_base/Utils').then((m) => m.FloatLeft));
export const FloatRight = dynamic(() => import('./_base/Utils').then((m) => m.FloatRight));
export const Hidden = dynamic(() => import('./_base/Utils').then((m) => m.Hidden));
export const HorizontalScroller = dynamic(() => import('./grid/HorizontalScroller'));
export const Loading = dynamic(() => import('./_base/Icon').then((m) => m.Loading));
export const NavigationLink = dynamic(() => import('./navigation/Navigation').then((m) => m.NavigationLink));
export const SecondaryNavigationLink = dynamic(() => import('./navigation/SecondaryNavigation').then((m) => m.SecondaryNavigationLink));
export const DashContainer = dynamic(() => import('./navigation/DashNavigation').then((m) => m.DashContainer));
export const DashNavigation = dynamic(() => import('./navigation/DashNavigation').then((m) => m.DashNavigation));
export const DashNavigationLink = dynamic(() => import('./navigation/DashNavigation').then((m) => m.DashNavigationLink));
export const DashNavigationText = dynamic(() => import('./navigation/DashNavigation').then((m) => m.DashNavigationText));
export const DashSidebar = dynamic(() => import('./navigation/DashNavigation').then((m) => m.DashSidebar));
export const DashSidebarDivider = dynamic(() => import('./navigation/DashNavigation').then((m) => m.DashSidebarDivider));
export const DashSidebarLink = dynamic(() => import('./navigation/DashNavigation').then((m) => m.DashSidebarLink));
export const DashSidebarAccordion = dynamic(() => import('./navigation/DashSidebarAccordion'));
export const DashSidebarText = dynamic(() => import('./navigation/DashNavigation').then((m) => m.DashSidebarText));
export const DashSidebarSwitcher = dynamic(() => import('./navigation/DashSidebarSwitcher'));
export const DashSidebarBox = dynamic(() => import('./navigation/DashNavigation').then((m) => m.DashSidebarBox));
export const FooterBar = dynamic(() => import('./footer/Footer').then((m) => m.FooterBar));
export const FooterLink = dynamic(() => import('./footer/Footer').then((m) => m.FooterLink));
export const DropdownDivider = dynamic(() => import('./dropdown/Dropdown').then((m) => m.DropdownDivider));
export const DropdownLink = dynamic(() => import('./dropdown/Dropdown').then((m) => m.DropdownLink));
export const NavDropdownFooter = dynamic(() => import('./navigation/NavDropdown').then((m) => m.NavDropdownFooter));
export const NavDropdownLink = dynamic(() => import('./navigation/NavDropdown').then((m) => m.NavDropdownLink));
export const NavDropdownTitle = dynamic(() => import('./navigation/NavDropdown').then((m) => m.NavDropdownTitle));

export const AnimeJS = dynamic(() => import('./_wrappers/AnimeJS'));
